### ISSUE TITLE
Identify issues with test.metpetdb.com

### ISSUE THREAD

**Issue by TheoBr** [metpetdb/interface_v2#11]
Seems like there's some strange things going on with the deployment at test.metpetdb.com, and there's no logging at the moment. I'll take a look as soon as I'm able

**Comment by TheoBr** [comment]
@kienankb , what kinds of logs would be helpful for me to set up on the test server? Apache?

**Comment by kienankb** [comment]
Fixed with refactor of code reading the app_variables.env files; previous method caused breaking problem between being used in development and being used in production.
