### ISSUE TITLE
Fix "Location" Search

### ISSUE THREAD

**Issue by TheoBr** [metpetdb/interface_v2#8]
Location search is relatively broken and the reason for such is unclear

**Comment by tamblc** [comment]
This is caused by a malformed query that is being sent to the API. The flask portion is sending empty fields which is causing a server error. I will update with specific line numbers shortly.

**Comment by kienankb** [comment]
Might be due to differing unicode standards--UTF-8 vs UTF-16.  Still investigating.

**Comment by kienankb** [comment]
Fixed with [PR#16](https://github.com/metpetdb/interface_v2/pull/16).
